version: '3.8'

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/app_development"
      REDIS_URL: "redis://redis:6379/1"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    volumes:
      - "db-data:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    volumes:
      - "redis-data:/data"

  migrations:
    build: .
    command: bash -c "bundle exec rails db:migrate db:seed"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/app_development"

volumes:
  db-data:
  redis-data: